from django.urls import path
from . import views


urlpatterns = [
    path('',views.home),
    path('home/',views.home),
    path('skill/',views.sort_page),
    path('life/',views.sort_page),
    path('food/',views.sort_page),
    path('msgboard/',views.msgboard),
    path('skill/python/',views.sort_page),
    path('skill/django/',views.sort_page),
    path('skill/vue/', views.sort_page),
    path('skill/html/',views.sort_page),
    path('skill/css/',views.sort_page),
    path('skill/js/',views.sort_page),
    path('life/essay/',views.sort_page),
    path('life/photo/',views.sort_page),
    path('food/teaching/',views.sort_page),
    path('food/share/',views.sort_page),
    path('skill/py001.html/',views.article_page),
    path('skill/py002.html/',views.article_page),
    path('skill/py003.html/',views.article_page),
    path('skill/py004.html/',views.article_page),
    path('skill/py005.html/',views.article_page),
    path('skill/py006.html/',views.article_page),
    path('skill/py007.html/',views.article_page),
    path('skill/py008.html/',views.article_page),
    path('skill/py009.html/',views.article_page),
    path('skill/py010.html/',views.article_page),
    path('skill/py011.html/',views.article_page),
    path('skill/py012.html/',views.article_page),
    path('skill/django001.html/',views.article_page),
    path('skill/vue001.html/',views.article_page),
    path('skill/html001.html/',views.article_page),
    path('skill/css001.html/',views.article_page),
    path('skill/js001.html/',views.article_page),
    path('life/essay001.html/',views.article_page),
    path('life/photo001.html/',views.article_page),
    path('food/share001.html/',views.article_page),
    path('food/share002.html/',views.article_page),
    path('food/teaching001.html/',views.article_page),
    path('food/teaching002.html/',views.article_page),

]