# Generated by Django 2.2.3 on 2019-08-01 02:50

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(help_text='skill or life or food', max_length=10, verbose_name='类别')),
                ('tag', models.CharField(help_text='python/django/vue/html/css/js/essay/photo/teaching/share', max_length=10, verbose_name='标签')),
                ('name', models.CharField(help_text='tag + articleNum', max_length=50, verbose_name='文章名')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('abstract', models.CharField(max_length=250, verbose_name='摘要')),
                ('content', mdeditor.fields.MDTextField()),
                ('time', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='留言时间')),
                ('content', models.CharField(max_length=250, verbose_name='内容')),
            ],
            options={
                'db_table': 'msg',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='评论时间')),
                ('content', models.CharField(max_length=250, verbose_name='内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogapp.Article')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
