# Generated by Django 2.2.3 on 2019-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgboard',
            name='message',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterModelTable(
            name='msgboard',
            table='msgboard',
        ),
    ]
